#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "===\n>> Pre-Push Hook: Running test"
npm run test
echo -e "===\n>> Pre-Push Hook: End running test"

echo -e "===\n>> Pre-Push Hook: Building application"
npm run build
echo -e "===\n>> Pre-Push Hook: Finish Building"
